# https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf

[general]
accounts = myaccount
maxsyncaccounts = 1
metadata = /mnt/mail/metadata
fsync = false

[Account myaccount]
localrepository = local-mail
remoterepository = remote-mail
# minutes, 1 day
autorefresh = 1440
quick = 7
# this will be done every time!
postsynchook = /bin/sh /mnt/config/write-keywords.sh

[Repository local-mail]
type = Maildir
localfolders = /mnt/mail/account
sync_deletes = no
nametrans = lambda folder: 'INBOX' if folder == '' else re.sub(r'^\.', '', folder)
# Useful flags worth preserving
customflag_a = $Forwarded
customflag_b = Forwarded
customflag_c = $MDNSent
customflag_d = $label1
customflag_e = $Label1
customflag_f = $Label4
customflag_g = $label5
customflag_h = receipt-handled

# Junk/nonjunk - pick canonical ones only if you care
customflag_i = NonJunk
customflag_j = $NotJunk
customflag_k = $Junk
customflag_l = Junk
customflag_m = NotJunk
customflag_n = $MailFlagBit0


[Repository remote-mail]
type = IMAP
remotehost = mail.example.com
remoteuser = mailuser
remotepassfile = /mnt/secret/password.conf
readonly = true
sslcacertfile = OS-DEFAULT
nametrans = lambda folder: '' if folder == 'INBOX' else '.' + folder
